### ISSUE TITLE
Crash When no cordinate found for searched location 

### ISSUE THREAD

**Issue by JigarRangani** [MorPfa/VibeCast#1]
here is issue when no coordinate found  

`Error during flow completion for getCoordinates: app.vibecast.data.remote.source.RemoteImageDataSourceImpl$EmptyApiResponseException: Coordinates list is empty. in Repository
2024-01-10 11:07:29.905 16824-16824 TestTag                 app.vibecast                         E  Error: app.vibecast.data.remote.source.RemoteImageDataSourceImpl$EmptyApiResponseException: Coordinates list is empty.
2024-01-10 11:07:29.916 16824-16824 AndroidRuntime          app.vibecast                         E  FATAL EXCEPTION: main
                                                                                                    Process: app.vibecast, PID: 16824
                                                                                                    app.vibecast.data.remote.source.RemoteImageDataSourceImpl$EmptyApiResponseException: Coordinates list is empty.
                                                                                                    	at app.vibecast.data.remote.source.RemoteWeatherDataSourceImpl$getCoordinates$1.invokeSuspend(RemoteWeatherDataSourceImpl.kt:50)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.UndispatchedCoroutine.afterResume(CoroutineContext.kt:270)
                                                                                                    	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                                                                                                    	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
                                                                                                    	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:100)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
                                                                                                    	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@8c59b63, Dispatchers.Main.immediate]`

**Comment by MorPfa** [comment]
Fixed by not emitting any value in case of invalid input which would previously lead to crash and instead showing snackbar with error message
